language: node_js
sudo: false
branches:
  except:
    - /^greenkeeper.*/
node_js:
  - 10
  - 8
  - 6
  - 4
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - travis_retry npm test
after_success:
  - npm run codecov

matrix:
  allow_failures:
  - node_js: 4
